services:
  - type: web
    name: module-funturine-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    plan: free
    branch: main
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
    
databases:
  - name: mongodb
    plan: free
